# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true # disabled in jekyll 3.0
# permalink: /:title/
# permalink: /:categories/:year/:month/:day/:title.xls

# Setup
title:            Andrei Solntsev
tagline:          Blog
description:      "Blog"
url:              https://asolntsev.github.io
baseurl:          /

author:
  name:           'Andrei Solntsev'
  url:            https://twitter.com/asolntsev

#gems:             [jekyll-paginate]
#paginate:         5
#paginate_path:    "page:num"

github:
  repo:           https://github.com/asolntsev/asolntsev.github.io

defaults:
  - 
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  - 
    scope:
      path: _posts/ru
    values:
      layout: default
      lang: ru
